// Node.js/SSO/react/src/App.jsx
import { useState } from "react";
import "./App.css";

function App() {
  const [count, setCount] = useState(0);
  const token = location.search.split("=")[1];
  if (!token) {
    fetch("http://localhost:3000/login?appId=Rs6s2aHi").then((res) => {
      location.href = res.url;
    });
  }

  return (
    <>
      <div>react 教育 5173</div>
    </>
  );
}

export default App;

// Node.js/SSO/vue/src/App.vue
<script setup>
const token = location.search.split("=")[1];
if (!token) {
  fetch("http://localhost:3000/login?appId=9LQ8Y3mB").then((res) => {
    location.href = res.url;
  });
}
</script>

<template>
  <div>vue 技术 5174</div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
